In [13]:
from sklearn.datasets import load_iris
import numpy as np

In [14]:
#loading the iris dataset
iris = load_iris()

In [15]:
#printing the metadata
print (iris.feature_names)
print (iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


In [16]:
#split the data
#removing three data points for later testing
test_idx = [0, 50, 100] #one of each species-> 3 examples to remove

#training set
train_target = np.delete(iris.target, test_idx)
train_features = np.delete(iris.data, test_idx, axis = 0) #axis = 0 row operation

#testing set
test_target = iris.target[test_idx]
test_features = iris.data[test_idx]

In [17]:
#define classifier, train
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_features, train_target)

In [18]:
#do testing and validate
print (test_target)
print(clf.predict(test_features))

[0 1 2]
[0 1 2]


In [28]:
#tree visualization
from sklearn.externals.six import StringIO
import pydot
dot_data = StringIO()
tree.export_graphviz(clf, 
                    out_file = dot_data,
                    feature_names = iris.feature_names,
                    class_names = iris.target_names,
                    filled = True, rounded = True,
                    impurity = False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
type(graph)
graph.write_pdf("iris.pdf")

AttributeError: 'list' object has no attribute 'write_pdf'